#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

BACKEND_DIR = Path(__file__).resolve().parents[1]
if str(BACKEND_DIR) not in sys.path:
    sys.path.insert(0, str(BACKEND_DIR))

from app.services.release_checklist_service import (  # noqa: E402
    build_release_checklist,
    save_release_checklist,
    save_release_checklist_markdown,
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Build release checklist from UAT and release drill artifacts.")
    parser.add_argument(
        "--uat-summary",
        required=True,
        help="Path to UAT summary.json generated by scripts/v2/uat.sh",
    )
    parser.add_argument(
        "--release-drill-report",
        default=None,
        help="Path to release drill report JSON generated by scripts/v2/release-drill.sh",
    )
    parser.add_argument(
        "--allow-without-release-drill",
        action="store_true",
        help="Allow generating checklist without release drill report.",
    )
    parser.add_argument(
        "--output",
        required=True,
        help="Output JSON path for release checklist.",
    )
    parser.add_argument(
        "--markdown-output",
        default=None,
        help="Optional Markdown output path for release checklist.",
    )
    parser.add_argument(
        "--title",
        default="智能巡检系统 V2 发布清单",
        help="Markdown report title.",
    )
    return parser.parse_args()


def _load_json(path: str) -> dict:
    return json.loads(Path(path).expanduser().resolve().read_text(encoding="utf-8"))


def main() -> int:
    args = parse_args()
    uat_summary = _load_json(args.uat_summary)
    release_drill_report = _load_json(args.release_drill_report) if args.release_drill_report else None

    checklist = build_release_checklist(
        uat_summary_path=args.uat_summary,
        uat_summary=uat_summary,
        release_drill_report_path=args.release_drill_report,
        release_drill_report=release_drill_report,
        allow_without_release_drill=args.allow_without_release_drill,
    )
    output_path = save_release_checklist(checklist, args.output)
    print(json.dumps(checklist.to_dict(), ensure_ascii=False, indent=2))
    print(f"[release-checklist] json report: {output_path}")

    if args.markdown_output:
        markdown_path = save_release_checklist_markdown(checklist, args.markdown_output, title=args.title)
        print(f"[release-checklist] markdown report: {markdown_path}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
