#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

BACKEND_DIR = Path(__file__).resolve().parents[1]
if str(BACKEND_DIR) not in sys.path:
    sys.path.insert(0, str(BACKEND_DIR))

from app.services.release_drill_report_service import (  # noqa: E402
    build_release_drill_report,
    save_release_drill_markdown,
    save_release_drill_report,
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Build cutover/release drill report from preflight + backfill.")
    parser.add_argument(
        "--preflight-summary",
        required=True,
        help="Path to preflight summary.json generated by scripts/v2/preflight.sh",
    )
    parser.add_argument(
        "--backfill-report",
        required=True,
        help="Path to backfill JSON report generated by scripts/v2/backfill.sh",
    )
    parser.add_argument(
        "--output",
        required=True,
        help="Output JSON path for release drill report.",
    )
    parser.add_argument(
        "--markdown-output",
        default=None,
        help="Optional output Markdown path for release drill report.",
    )
    parser.add_argument(
        "--title",
        default="智能巡检系统 V2 上线演练报告",
        help="Markdown report title.",
    )
    return parser.parse_args()


def _load_json(path: str) -> dict:
    resolved = Path(path).expanduser().resolve()
    return json.loads(resolved.read_text(encoding="utf-8"))


def main() -> int:
    args = parse_args()
    preflight_summary = _load_json(args.preflight_summary)
    backfill_report = _load_json(args.backfill_report)

    report = build_release_drill_report(
        preflight_summary_path=args.preflight_summary,
        preflight_summary=preflight_summary,
        backfill_report_path=args.backfill_report,
        backfill_report=backfill_report,
    )
    output_path = save_release_drill_report(report, args.output)
    print(json.dumps(report.to_dict(), ensure_ascii=False, indent=2))
    print(f"[release-drill] json report: {output_path}")

    if args.markdown_output:
        markdown_path = save_release_drill_markdown(report, args.markdown_output, title=args.title)
        print(f"[release-drill] markdown report: {markdown_path}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
